/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Student;

import Login.ChangePassword;
import Login.Login;
import Login.MyData;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Utsho
 */
public class StudentMenu extends javax.swing.JFrame {

    /**
     * Creates new form StudentMenu
     */
    public StudentMenu() {
        initComponents();
//        initInformation();
    }
    public static String id;
    static StudentMenu sm = new StudentMenu();
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        back = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        myCourse = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        cgpa = new javax.swing.JLabel();
        program = new javax.swing.JLabel();
        section = new javax.swing.JLabel();
        batch = new javax.swing.JLabel();
        studentid = new javax.swing.JLabel();
        name = new javax.swing.JLabel();
        chengePassword = new javax.swing.JButton();
        coursePlan = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        credit = new javax.swing.JLabel();
        courseDetails = new javax.swing.JButton();
        routine = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Student");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 153, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 153, 0));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/student.png"))); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, 380, 340));

        back.setBackground(getBackground());
        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/back_button.png"))); // NOI18N
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        jPanel2.add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 40, 40));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, 550));

        jPanel3.setBackground(new java.awt.Color(0, 153, 153));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 102));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Make the world better");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 370, 70));
        jPanel3.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 390, 10));

        jPanel3.add(myCourse, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, 110, 40));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 153));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Batch:");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 210, 60, 20));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 153));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("ID:");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 190, 40, 20));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 153));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Program:");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 250, 70, -1));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 153));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Credit Completed:");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 120, 20));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 153));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Section: ");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 230, 80, 20));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 153));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Name:");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 170, 40, 20));

        cgpa.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        cgpa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel3.add(cgpa, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 270, 130, -1));

        program.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        program.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel3.add(program, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 250, 130, -1));

        section.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        section.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel3.add(section, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 230, 130, -1));

        batch.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        batch.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel3.add(batch, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 210, 130, -1));

        studentid.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        studentid.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel3.add(studentid, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 190, 130, -1));

        name.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        name.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        name.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                nameAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jPanel3.add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 170, 130, -1));

        chengePassword.setBackground(new java.awt.Color(255, 255, 0));
        chengePassword.setFont(new java.awt.Font("Bookman Old Style", 1, 14)); // NOI18N
        chengePassword.setForeground(new java.awt.Color(0, 0, 0));
        chengePassword.setText("Change Password");
        chengePassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chengePasswordActionPerformed(evt);
            }
        });
        jPanel3.add(chengePassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 470, 210, 30));

        coursePlan.setBackground(new java.awt.Color(255, 255, 0));
        coursePlan.setFont(new java.awt.Font("Bookman Old Style", 1, 14)); // NOI18N
        coursePlan.setForeground(new java.awt.Color(0, 0, 0));
        coursePlan.setText("Open Course-Plan");
        coursePlan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                coursePlanActionPerformed(evt);
            }
        });
        jPanel3.add(coursePlan, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 350, 210, 30));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 153));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("CGPA:");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 270, 60, 20));

        credit.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        credit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        credit.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                creditAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jPanel3.add(credit, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 290, 90, -1));

        courseDetails.setBackground(new java.awt.Color(255, 255, 0));
        courseDetails.setFont(new java.awt.Font("Bookman Old Style", 1, 14)); // NOI18N
        courseDetails.setForeground(new java.awt.Color(0, 0, 0));
        courseDetails.setText("Open Course Details");
        courseDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                courseDetailsActionPerformed(evt);
            }
        });
        jPanel3.add(courseDetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 390, 210, 30));

        routine.setBackground(new java.awt.Color(255, 255, 0));
        routine.setFont(new java.awt.Font("Bookman Old Style", 1, 14)); // NOI18N
        routine.setForeground(new java.awt.Color(0, 0, 0));
        routine.setText("Todays Class");
        routine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                routineActionPerformed(evt);
            }
        });
        jPanel3.add(routine, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 430, 210, 30));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, -10, 400, 540));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 840, 520));

        setSize(new java.awt.Dimension(845, 546));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        this.setVisible(false);
        new Login().setVisible(true);
    }//GEN-LAST:event_backActionPerformed

    private void chengePasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chengePasswordActionPerformed
        sm.setVisible(false);
        ChangePassword.changePassword();
    }//GEN-LAST:event_chengePasswordActionPerformed
    private void updateCourseList(String batch) throws Exception{
        try{
            ResultSet courseList = MyData.updateCombo(batch, "Null");
            if(courseList.next()){
                myCourse.addItem(courseList.getString("course_1"));
                myCourse.addItem(courseList.getString("course_2"));
                myCourse.addItem(courseList.getString("course_3"));
                myCourse.addItem(courseList.getString("course_4"));
            }
            else{
                new Exception();
            }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, "No Course Assigned");
        }
    }
    
    private void nameAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_nameAncestorAdded
        
        try {
            ResultSet list = MyData.getResultSet("student", id, "hi");
            list.next();
            updateCourseList(String.valueOf(list.getInt("batch")));
            name.setText(list.getString("name"));
            studentid.setText(String.valueOf(list.getInt("id")));
            batch.setText(String.valueOf(list.getString("batch")));
            section.setText(list.getString("section"));
            program.setText(list.getString("department"));
            cgpa.setText(String.valueOf(list.getDouble("cgpa")));
            credit.setText(String.valueOf(list.getDouble("total_credit")));
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "You are not a student yet! :(");
        }
        
    }//GEN-LAST:event_nameAncestorAdded

    private void coursePlanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_coursePlanActionPerformed
        String course = String.valueOf(myCourse.getSelectedItem());
        try {
            ResultSet li = MyData.getResultSet(course, "attendance");
            li.next();
            String url = li.getString("courseplan");
            java.awt.Desktop.getDesktop().browse(java.net.URI.create(url));
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "cannot load course-plan");
        }
    }//GEN-LAST:event_coursePlanActionPerformed

    private void creditAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_creditAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_creditAncestorAdded

    private void courseDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_courseDetailsActionPerformed
        String courseTeacher = MyData.getShortName(String.valueOf(myCourse.getSelectedItem()), null);
        //Print teachers name from teacher info
//        JOptionPane.showMessageDialog(null, courseTeacher);
        try{
            ResultSet data = MyData.getResultSet(String.valueOf(myCourse.getSelectedItem()), "mark", id, "null");
            data.next();
            JOptionPane.showMessageDialog(null, " Attendance Mark: " + String.valueOf(data.getDouble("attendance")) + 
                    "\n" + "Assignment Mark: " + String.valueOf(data.getDouble("assignment")) +
                    "\n" + " Tutorial 1 Mark: " + String.valueOf(data.getDouble("tutorial_1")) +
                    "\n" + "   Mid-term Mark: " + String.valueOf(data.getDouble("midterm")) +
                    "\n" + " Tutorial 2 Mark: " + String.valueOf(data.getDouble("tutorial_2")) +
                    "\n" + "Sem-Final Mark: " + String.valueOf(data.getDouble("finalterm")) +
                    "\n" + "                       GP: " + String.valueOf(data.getDouble("cgpa")));
        } catch(Exception e){
            JOptionPane.showMessageDialog(null, "Cannot get selected Course information");
        }
    }//GEN-LAST:event_courseDetailsActionPerformed

    private void routineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_routineActionPerformed
//        this.setVisible(false);
        try{
            ResultSet list = MyData.getResultSet("student", id, "hi");
            list.next();
            StudentRoutine.studentRoutine(String.valueOf(list.getString("batch")));
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Routine cannot open");
        }
//            list.next();
//        StudentRoutine.studentRoutine(String);
    }//GEN-LAST:event_routineActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void student_menu() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            sm.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JLabel batch;
    private javax.swing.JLabel cgpa;
    private javax.swing.JButton chengePassword;
    private javax.swing.JButton courseDetails;
    private javax.swing.JButton coursePlan;
    private javax.swing.JLabel credit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JComboBox<String> myCourse;
    private javax.swing.JLabel name;
    private javax.swing.JLabel program;
    private javax.swing.JButton routine;
    private javax.swing.JLabel section;
    private javax.swing.JLabel studentid;
    // End of variables declaration//GEN-END:variables
}
