package Admin.jframe;

import Admin.database.PendingStudentsDatabase;
import Students.Student;
import java.awt.Point;
import java.awt.event.MouseEvent;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionListener;
import javax.swing.event.ListSelectionEvent;
import javax.swing.table.DefaultTableModel;

public class PendingStudents extends javax.swing.JFrame {
    public static PendingStudents frm;
    
    static Vector<Student> data;
    public PendingStudents(Vector<Student> data){
        this.data=data;
    }
    //----------------------------------------------------------------------
    public PendingStudents() {
        model= new DefaultTableModel(t, col);
	row=column=-1;
        initComponents();
        
        for(int i=0; i<this.data.size(); i++)
        {
            model.addRow(new Object[]{i+1, data.elementAt(i).name, data.elementAt(i).program});
        }
    }
    //------------------------------------------------------------------------




    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
//--------------------------------------------------------------------------
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        stdntTbl = new javax.swing.JTable();
        dltrow6 = new javax.swing.JButton();
        admt = new javax.swing.JButton();
        details = new javax.swing.JButton();
        Back = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
	jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        stdntTbl.setModel(model);
        stdntTbl.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
 	stdntTbl.setCellSelectionEnabled(true);  
            ListSelectionModel select= stdntTbl.getSelectionModel();  
            select.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);  
            select.addListSelectionListener(new ListSelectionListener() {  
              public void valueChanged(ListSelectionEvent e) {  
                String Data = null;  
                row = stdntTbl.getSelectedRow();  
                column = stdntTbl.getSelectedColumn();  
              }       
            });  
        jScrollPane1.setViewportView(stdntTbl);

        dltrow6.setBackground(new java.awt.Color(204, 204, 204));
        dltrow6.setForeground(new java.awt.Color(0, 0, 0));
        dltrow6.setText("Delete data of selected Row");
        dltrow6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dltrow6ActionPerformed(evt);
            }
        });

        admt.setBackground(new java.awt.Color(204, 204, 204));
        admt.setForeground(new java.awt.Color(0, 0, 0));
        admt.setText("Admit data of selected Row");
        admt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                admtActionPerformed(evt);
            }
        });

        details.setBackground(new java.awt.Color(204, 204, 204));
        details.setForeground(new java.awt.Color(0, 0, 0));
        details.setText("See details of selected Row");
        details.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                detailsActionPerformed(evt);
            }
        });

        Back.setText("Back");
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(65, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(dltrow6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1)
                    .addComponent(admt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(details, javax.swing.GroupLayout.PREFERRED_SIZE, 453, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(59, 59, 59))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(244, 244, 244)
                .addComponent(Back)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dltrow6)
                .addGap(11, 11, 11)
                .addComponent(admt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(details)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Back)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
//--------------------------------------------------------------------------









    private void dltrow6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dltrow6ActionPerformed

        try
        {
            int rv=Integer.parseInt(stdntTbl.getValueAt(row, 0).toString());
            model.removeRow(row);
            Student.deletePending(Integer.toString(data.elementAt(rv-1).admissionId));
        }
        catch(Exception ex)
        {

            JOptionPane.showMessageDialog(null,"Please select a valid row... "+ex);
        }
    }//GEN-LAST:event_dltrow6ActionPerformed







//--------------------------------------------------------------------------
    private void admtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_admtActionPerformed
        try
        {
            int indx=Integer.parseInt(stdntTbl.getValueAt(row, 0).toString());
            int rv=Integer.parseInt(stdntTbl.getValueAt(row, 0).toString());
            new AdmitStudent().Show(data.elementAt(rv-1));
        }
        catch(Exception ex)
        {
            JOptionPane.showMessageDialog(null,"Please select a valid row... "+ex);
        }
    }//GEN-LAST:event_admtActionPerformed
//--------------------------------------------------------------------------







    private void detailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_detailsActionPerformed

    }//GEN-LAST:event_detailsActionPerformed

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        frm.setVisible(false);
        Admission_preview.preview.setVisible(true);
    }//GEN-LAST:event_BackActionPerformed

    /**
     * @param args the command line arguments
     */







//--------------------------------------------------------------------------
    public void Show(Vector<Student> obj)
//    public static void main(String args[]) 
    {
        data=obj;
       
/* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PendingStudents.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PendingStudents.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PendingStudents.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PendingStudents.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               frm=new PendingStudents();
               frm.setVisible(true);
            }
        });
    }
//--------------------------------------------------------------------------







    public static int row, column;
    static private Vector<Vector<String>> t[][];
    static String col[]={"Sl. no.", "Name", "Program"};
    static DefaultTableModel model= new DefaultTableModel();

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back;
    private javax.swing.JButton admt;
    private javax.swing.JButton details;
    private javax.swing.JButton dltrow6;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable stdntTbl;
    // End of variables declaration//GEN-END:variables
}
