/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Login;
import Admin.jframe.EditManu;
import Converter.Converter;
import javax.swing.JOptionPane;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import teacher.Teacher_menu;
import Student.StudentMenu;
import Calculator.Calculator;
import Students.Jframe.Admission;
/**
 *
 * @author Utsho
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form java
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        username = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        password = new javax.swing.JPasswordField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        asStudent = new javax.swing.JButton();
        asTeacher = new javax.swing.JButton();
        asAdmin = new javax.swing.JButton();
        Calculator = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        converter = new javax.swing.JButton();
        calculator = new javax.swing.JButton();
        registration = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");
        setName("login"); // NOI18N
        setResizable(false);

        jPanel2.setBackground(new java.awt.Color(0, 102, 102));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Bookman Old Style", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Login");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 450, 70));

        jSeparator1.setBackground(new java.awt.Color(255, 0, 0));
        jSeparator1.setForeground(new java.awt.Color(255, 0, 102));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 450, 10));

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Login/username.png"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 130, 50, 40));

        username.setBackground(new java.awt.Color(255, 255, 255));
        username.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        username.setForeground(new java.awt.Color(0, 0, 0));
        username.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 140, 130, -1));

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Login/password.png"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 180, 50, 40));

        password.setBackground(new java.awt.Color(255, 255, 255));
        password.setForeground(new java.awt.Color(0, 0, 0));
        password.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 190, 130, -1));

        jLabel6.setFont(new java.awt.Font("Bookman Old Style", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 51, 51));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Password: ");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 170, 120, -1));

        jLabel7.setFont(new java.awt.Font("Bookman Old Style", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 51, 51));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Username: ");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 120, 120, -1));

        asStudent.setBackground(new java.awt.Color(0, 51, 51));
        asStudent.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        asStudent.setForeground(new java.awt.Color(255, 255, 0));
        asStudent.setText("Student");
        asStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                asStudentActionPerformed(evt);
            }
        });
        jPanel1.add(asStudent, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 290, 100, -1));

        asTeacher.setBackground(new java.awt.Color(0, 51, 51));
        asTeacher.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        asTeacher.setForeground(new java.awt.Color(255, 255, 0));
        asTeacher.setText("Teacher");
        asTeacher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                asTeacherActionPerformed(evt);
            }
        });
        jPanel1.add(asTeacher, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 290, 100, -1));

        asAdmin.setBackground(new java.awt.Color(0, 51, 51));
        asAdmin.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        asAdmin.setForeground(new java.awt.Color(255, 255, 0));
        asAdmin.setText("Admin");
        asAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                asAdminActionPerformed(evt);
            }
        });
        jPanel1.add(asAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, 100, -1));

        jPanel2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 20, 480, 400));

        Calculator.setBackground(new java.awt.Color(0, 204, 0));
        Calculator.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        Calculator.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 134, -1, -1));

        jLabel3.setFont(new java.awt.Font("Courier New", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Login/login.png"))); // NOI18N
        jLabel3.setMaximumSize(new java.awt.Dimension(100, 100));
        jLabel3.setMinimumSize(new java.awt.Dimension(100, 100));
        jLabel3.setPreferredSize(new java.awt.Dimension(100, 100));
        Calculator.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, 219, 190));

        converter.setBackground(new java.awt.Color(0, 0, 204));
        converter.setFont(new java.awt.Font("Bookman Old Style", 1, 18)); // NOI18N
        converter.setForeground(new java.awt.Color(255, 255, 51));
        converter.setText("Converter");
        converter.setToolTipText("");
        converter.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        converter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                converterActionPerformed(evt);
            }
        });
        Calculator.add(converter, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 290, -1, -1));

        calculator.setBackground(new java.awt.Color(0, 0, 204));
        calculator.setFont(new java.awt.Font("Bookman Old Style", 1, 18)); // NOI18N
        calculator.setForeground(new java.awt.Color(255, 255, 51));
        calculator.setText("Calculator");
        calculator.setToolTipText("");
        calculator.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        calculator.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculatorActionPerformed(evt);
            }
        });
        Calculator.add(calculator, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 290, -1, -1));

        registration.setBackground(new java.awt.Color(0, 0, 204));
        registration.setFont(new java.awt.Font("Bookman Old Style", 1, 18)); // NOI18N
        registration.setForeground(new java.awt.Color(255, 255, 51));
        registration.setText("Registration");
        registration.setToolTipText("");
        registration.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        registration.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrationActionPerformed(evt);
            }
        });
        Calculator.add(registration, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 350, -1, -1));

        jPanel2.add(Calculator, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 390, 460));

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        setSize(new java.awt.Dimension(851, 502));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    
    public static void worngPassword(){
        JOptionPane.showMessageDialog(null, "Worng Username or Password\n Try Again.");
    }

    /**
     *
     * @param profession
     * @return
     * @throws Exception
     */
    private boolean checkPassword(String profession) throws Exception{
        try{
            String pass = String.valueOf(password.getPassword());
            if (profession.equals("teacher")){
                Teacher_menu.username = username.getText();
            }
            else if(profession.equals("student")){
                StudentMenu.id = username.getText();
            }
            ResultSet res;
            res = MyData.matchPassword(username.getText(), pass, profession);
            return res.next();
        }
        catch(SQLException e){
            JOptionPane.showMessageDialog(null, "No Database Found");
            return false;
        }
    }
    
    private void asAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_asAdminActionPerformed
        try {
            if(checkPassword("admin") == true){
                this.setVisible(false);
                new EditManu().admin();
                
            }
            else{
                worngPassword();
            }
        } catch (Exception ex) {
            // NEVER USED
//            worngPassword();
            JOptionPane.showMessageDialog(null, "admin problem \n " + ex);
        }
    }//GEN-LAST:event_asAdminActionPerformed

    private void asTeacherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_asTeacherActionPerformed
        try {
            if(checkPassword("teacher") == true){
                this.setVisible(false);
                new Teacher_menu().setVisible(true);
                
            }
            else{
                worngPassword();
            }
        } catch (Exception ex) {
            // NEVER USED
            worngPassword();
        }
    }//GEN-LAST:event_asTeacherActionPerformed

    private void asStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_asStudentActionPerformed
        try {
            if(checkPassword("student") == true){
                this.setVisible(false);
                new StudentMenu().setVisible(true);
                
            }
            else{
                worngPassword();
            }
        } catch (Exception ex) {
            // NEVER USED
            worngPassword();
        }
    }//GEN-LAST:event_asStudentActionPerformed

    private void calculatorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculatorActionPerformed
        this.setVisible(false);
        new Calculator().setVisible(true);
        
    }//GEN-LAST:event_calculatorActionPerformed

    private void converterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_converterActionPerformed
        this.setVisible(false);
        Converter.converter();
    }//GEN-LAST:event_converterActionPerformed

    private void registrationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrationActionPerformed
        this.setVisible(false);
        new Admission().setVisible(true);
    }//GEN-LAST:event_registrationActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void run() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Login().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Calculator;
    private javax.swing.JButton asAdmin;
    private javax.swing.JButton asStudent;
    private javax.swing.JButton asTeacher;
    private javax.swing.JButton calculator;
    private javax.swing.JButton converter;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPasswordField password;
    private javax.swing.JButton registration;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables
}
