package Converter;


import Converter.Mass;
import Converter.Fuel_Economy;
import Converter.Frequency;
import Converter.Energy;
import Login.Login;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Windows 10
 */
public class Converter extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public Converter() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        cnv = new javax.swing.JComboBox<>();
        back = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cnv.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cnv.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Energy", "Frequency", "Fuel Economy", "Mass", "Pressure", "Speed", "Temperature", "Time" }));
        cnv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cnvActionPerformed(evt);
            }
        });
        jPanel1.add(cnv, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 160, 155, 42));

        back.setBackground(getBackground());
        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/back_button.png"))); // NOI18N
        back.setBorder(null);
        back.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        jPanel1.add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 40, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 510, 380));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public static Energy energy_obj = new Energy();
    public static Speed speed_obj = new Speed();
    public static Frequency frequency_obj = new Frequency();
    public static Mass  mass_obj = new Mass();
    public static Time time_obj = new Time();
    public static Fuel_Economy fuel_economy_obj = new Fuel_Economy();
    public static Pressure pressure_obj = new Pressure();
    public static Temperature temperature_obj = new Temperature();
    public static Converter object;
    
    private void cnvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cnvActionPerformed
        // TODO add your handling code here:
        
        if(cnv.getSelectedIndex()==0){
            object.setVisible(false);
            energy_obj.Energyfun();
        }
        else if(cnv.getSelectedIndex()==1){
            object.setVisible(false);
            frequency_obj.Frequencyfun();
        }
        else if(cnv.getSelectedIndex()==2){
            object.setVisible(false);
            fuel_economy_obj.Fuel_Economyfun();
        }
        else if(cnv.getSelectedIndex()==3){
            object.setVisible(false);
            mass_obj.Massfun();
        }
        else if(cnv.getSelectedIndex()==4){
            object.setVisible(false);
            pressure_obj.Pressurefun();
            //connected
        }
        else if(cnv.getSelectedIndex()==5){
            object.setVisible(false);
            speed_obj.Speedfun();
        }
        else if(cnv.getSelectedIndex()==6){
            object.setVisible(false);
            temperature_obj.Temperaturefun();            
        }
        else if(cnv.getSelectedIndex()==7){
            object.setVisible(false);            
            time_obj.Timefun();
        }       
    }//GEN-LAST:event_cnvActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        this.setVisible(false);
        Login.run();
    }//GEN-LAST:event_backActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void converter() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Converter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Converter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Converter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Converter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            object = new Converter();
            object.setVisible(true);
            //new Converter().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JComboBox<String> cnv;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
