package Converter;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Windows 10
 */
public class Frequency extends javax.swing.JFrame {

    /**
     * Creates new form Frequency
     */
    public Frequency() {
        initComponents();
    }
    public void same(){
        double var = Double.parseDouble(textfrom.getText().toString());
        String var2 = Double.toString(var);
        textto.setText(var2);
    }
    public void hertz_kilohertz(){
       double var = Double.parseDouble(textfrom.getText().toString());
       var = var/1000;
       String var2 = Double.toString(var);
       textto.setText(var2);
   }

    public void hertz_megahertz(){
       double var = Double.parseDouble(textfrom.getText().toString());
       var = var/1000000;
       String var2 = Double.toString(var);
       textto.setText(var2);
   }


    public void hertz_gigahertz(){
       double var = Double.parseDouble(textfrom.getText().toString());
       var = var/1000000000;
       String var2 = Double.toString(var);
       textto.setText(var2);
   }

    public void kilohertz_hertz(){
       double var = Double.parseDouble(textfrom.getText().toString());
       var = var*1000;
       String var2 = Double.toString(var);
       textto.setText(var2);
   }
   
    public void kilohertz_megahertz(){
       double var = Double.parseDouble(textfrom.getText().toString());
       var = var/1000;
       String var2 = Double.toString(var);
       textto.setText(var2);
   }
  
    public void kilohertz_gigahertz(){
       double var = Double.parseDouble(textfrom.getText().toString());
       var = var/1000000;
       String var2 = Double.toString(var);
       textto.setText(var2);
   }


  
    public void megahertz_hertz(){
       double var = Double.parseDouble(textfrom.getText().toString());
       var = var*1000000;
       String var2 = Double.toString(var);
       textto.setText(var2);
   }

   public void megahertz_kilohertz(){
       double var = Double.parseDouble(textfrom.getText().toString());
       var = var*1000;
       String var2 = Double.toString(var);
       textto.setText(var2);
   }
 public void megahertz_gigahertz(){
       double var = Double.parseDouble(textfrom.getText().toString());
       var = var/1000;
       String var2 = Double.toString(var);
       textto.setText(var2);
   }

 public void gigahertz_hertz(){
       double var = Double.parseDouble(textfrom.getText().toString());
       var = var*1000000000;
       String var2 = Double.toString(var);
       textto.setText(var2);
   }

 public void gigahertz_megahertz(){
       double var = Double.parseDouble(textfrom.getText().toString());
       var = var*1000;
       String var2 = Double.toString(var);
       textto.setText(var2);
   }
 public void gigahertz_kilohertz(){
       double var = Double.parseDouble(textfrom.getText().toString());
       var = var*100000;
       String var2 = Double.toString(var);
       textto.setText(var2);
   }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        frqto = new javax.swing.JComboBox<>();
        frqfrom = new javax.swing.JComboBox<>();
        textfrom = new javax.swing.JTextField();
        textto = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        Back = new javax.swing.JButton();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 51, 51));

        frqto.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        frqto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Hertz", "Kilohertz", "Megahertz", "Gigahertz" }));

        frqfrom.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        frqfrom.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Hertz", "Kilohertz", "Megahertz", "Gigahertz" }));

        textfrom.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        textto.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("Enter");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        Back.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Back.setText("Back");
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(Back)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(202, 202, 202)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(textfrom, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(frqfrom, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textto, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(frqto, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(164, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(Back)
                .addGap(62, 62, 62)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textto, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textfrom, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(frqto, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(frqfrom, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(122, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(frqfrom.getSelectedIndex() == frqto.getSelectedIndex()){
                    same();
                }
        else{
            if(frqfrom.getSelectedIndex()==0 && frqto.getSelectedIndex()==1){
                    hertz_kilohertz();
                }
            else if(frqfrom.getSelectedIndex()==0 && frqto.getSelectedIndex()==2){
                    hertz_megahertz();
                }
            else if(frqfrom.getSelectedIndex()==0 && frqto.getSelectedIndex()==3){
                    hertz_gigahertz();
                }
            
            
            
            else if(frqfrom.getSelectedIndex()==1 && frqto.getSelectedIndex()==0){
                    kilohertz_hertz();
                }
            else if(frqfrom.getSelectedIndex()==1 && frqto.getSelectedIndex()==2){
                    kilohertz_megahertz();
                }
            else if(frqfrom.getSelectedIndex()==1 && frqto.getSelectedIndex()==3){
                    kilohertz_gigahertz();
                }
            
            
            
            
            else if(frqfrom.getSelectedIndex()==2 && frqto.getSelectedIndex()==0){
                    megahertz_hertz();
                }
            else if(frqfrom.getSelectedIndex()==2 && frqto.getSelectedIndex()==1){
                    megahertz_kilohertz();
                }
            else if(frqfrom.getSelectedIndex()==2 && frqto.getSelectedIndex()==3){
                    megahertz_gigahertz();
                }
            
            
            else if(frqfrom.getSelectedIndex()==3 && frqto.getSelectedIndex()==0){
                    gigahertz_hertz();
                }
            else if(frqfrom.getSelectedIndex()==3 && frqto.getSelectedIndex()==1){
                    gigahertz_megahertz();
                }
            else if(frqfrom.getSelectedIndex()==3 && frqto.getSelectedIndex()==2){
                    gigahertz_kilohertz();
                }
            
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        // TODO add your handling code here:
        Converter.object.setVisible(true);
        obj.setVisible(false);
    }//GEN-LAST:event_BackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static Frequency obj = null ;
    public static void Frequencyfun() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frequency.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frequency.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frequency.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frequency.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                obj = new Frequency();
                obj.setVisible(true);
                //new Frequency().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back;
    private javax.swing.JComboBox<String> frqfrom;
    private javax.swing.JComboBox<String> frqto;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField textfrom;
    private javax.swing.JTextField textto;
    // End of variables declaration//GEN-END:variables
}
