package Converter;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Windows 10
 */
public class Fuel_Economy extends javax.swing.JFrame {

    /**
     * Creates new form Fuel_Economy
     */
    public Fuel_Economy() {
        initComponents();
    }
    public void same(){
        double var = Double.parseDouble(textfrom.getText().toString());
        String var2 = Double.toString(var);
        textto.setText(var2);
    }
    // time
    // nanosecond
    // fuel economy
    // miles per gallon

    public void milesPerGallon_milesPerGallon_imperial() {
        double var = Double.parseDouble(textfrom.getText().toString());
        var = var*1.201;
        String var2 = Double.toString(var);
        textto.setText(var2);
    }

    public void milesPerGallon_kiloPerLiter() {
        double var = Double.parseDouble(textfrom.getText().toString());
        var = var/2.352;
        String var2 = Double.toString(var);
        textto.setText(var2);
    }

    public void milesPerGallon_LiterPer100Kilometer() {
        double var = Double.parseDouble(textfrom.getText().toString());
        var =  235.215/var;
        String var2 = Double.toString(var);
        textto.setText(var2);
    }
    //milesPerGallon_imperial
    public void milesPerGallon_imperial_milesPerGallon() {
        double var = Double.parseDouble(textfrom.getText().toString());
        var = var/1.201;
        String var2 = Double.toString(var);
        textto.setText(var2);
    }

    public void milesPerGallon_imperial_kiloPerLiter() {
        double var = Double.parseDouble(textfrom.getText().toString());
        var = var/2.825;
        String var2 = Double.toString(var);
        textto.setText(var2);
    }

    public void milesPerGallon_imperial_LiterPer100Kilometer() {
        double var = Double.parseDouble(textfrom.getText().toString());
        var =  282.481/var;
        String var2 = Double.toString(var);
        textto.setText(var2);
    }
    // kiloPerLiter
    public void kiloPerLiter_milesPerGallon() {
        double var = Double.parseDouble(textfrom.getText().toString());
        var = var*2.352;
        String var2 = Double.toString(var);
        textto.setText(var2);
    }

    public void kiloPerLiter_milesPerGallon_imperial() {
        double var = Double.parseDouble(textfrom.getText().toString());
        var = var*2.825;
        String var2 = Double.toString(var);
        textto.setText(var2);
    }

    public void kiloPerLiter_LiterPer100Kilometer() {
        double var = Double.parseDouble(textfrom.getText().toString());
        var = 100/var;
        String var2 = Double.toString(var);
        textto.setText(var2);
    }
    // LiterPer100Kilometer
    public void LiterPer100Kilometer_milesPerGallon() {
        double var = Double.parseDouble(textfrom.getText().toString());
        var = 235.215/var;
        String var2 = Double.toString(var);
        textto.setText(var2);
    }

    public void LiterPer100Kilometer_milesPerGallon_imperial() {
        double var = Double.parseDouble(textfrom.getText().toString());
        var = 282.481/var;
        String var2 = Double.toString(var);
        textto.setText(var2);
    }

    public void LiterPer100Kilometer_kiloPerLiter() {
        double var = Double.parseDouble(textfrom.getText().toString());
        var = 100/var;
        String var2 = Double.toString(var);
        textto.setText(var2);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        fcfrom = new javax.swing.JComboBox<>();
        fcto = new javax.swing.JComboBox<>();
        textfrom = new javax.swing.JTextField();
        textto = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        Back = new javax.swing.JButton();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));

        fcfrom.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        fcfrom.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Miles per gallon", "Miles per gallon(imperia)l", "kilo per liter", "Liter per100 kilometer" }));

        fcto.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        fcto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Miles per gallon", "Miles per gallon(imperia)l", "kilo per liter", "Liter per100 kilometer" }));

        textfrom.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        textto.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("Enter");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        Back.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Back.setText("Back");
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(textfrom)
                    .addComponent(fcfrom, 0, 169, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 121, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(fcto, 0, 150, Short.MAX_VALUE)
                    .addComponent(textto))
                .addGap(96, 96, 96))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(237, 237, 237)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(Back, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(Back, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 99, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textfrom, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textto, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fcfrom, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fcto, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(111, 111, 111))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if(fcfrom.getSelectedIndex() == fcto.getSelectedIndex()){
                    same();
                }
        else{
            if(fcfrom.getSelectedIndex()==0 && fcto.getSelectedIndex()==1){
                    milesPerGallon_milesPerGallon_imperial();
                }
            else if(fcfrom.getSelectedIndex()==0 && fcto.getSelectedIndex()==2){
                milesPerGallon_kiloPerLiter();
            }
            else if(fcfrom.getSelectedIndex()==0 && fcto.getSelectedIndex()==3){
                milesPerGallon_LiterPer100Kilometer();
            }
            else if(fcfrom.getSelectedIndex()==1 && fcto.getSelectedIndex()==0){
                milesPerGallon_imperial_milesPerGallon();
            }
            else if(fcfrom.getSelectedIndex()==1 && fcto.getSelectedIndex()==2){
                milesPerGallon_imperial_kiloPerLiter();
            }else if(fcfrom.getSelectedIndex()==1 && fcto.getSelectedIndex()==3){
                milesPerGallon_imperial_LiterPer100Kilometer();
            }
            else if(fcfrom.getSelectedIndex()==2 && fcto.getSelectedIndex()==0){
                kiloPerLiter_milesPerGallon();
            }
            else if(fcfrom.getSelectedIndex()==2 && fcto.getSelectedIndex()==1){
                kiloPerLiter_milesPerGallon_imperial();
            }else if(fcfrom.getSelectedIndex()==2 && fcto.getSelectedIndex()==3){
                kiloPerLiter_LiterPer100Kilometer();
            }
            else if(fcfrom.getSelectedIndex()==3 && fcto.getSelectedIndex()==0){
                LiterPer100Kilometer_milesPerGallon();
            }
            else if(fcfrom.getSelectedIndex()==3 && fcto.getSelectedIndex()==1){
                LiterPer100Kilometer_milesPerGallon_imperial();
            }else if(fcfrom.getSelectedIndex()==3 && fcto.getSelectedIndex()==2){
                LiterPer100Kilometer_kiloPerLiter();
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        // TODO add your handling code here:
        Converter.object.setVisible(true);
        obj.setVisible(false);
    }//GEN-LAST:event_BackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static Fuel_Economy obj = null ; 
    public static void Fuel_Economyfun() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Fuel_Economy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Fuel_Economy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Fuel_Economy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Fuel_Economy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new Fuel_Economy().setVisible(true);
                obj = new Fuel_Economy();
                obj.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back;
    private javax.swing.JComboBox<String> fcfrom;
    private javax.swing.JComboBox<String> fcto;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField textfrom;
    private javax.swing.JTextField textto;
    // End of variables declaration//GEN-END:variables
}
